/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    java
    application
    id("com.gradleup.shadow") version "8.3.4"
}

group="org.mongodb"
version="0.2-SNAPSHOT"
description="poc-driver"

java {
    sourceCompatibility = JavaVersion.VERSION_17
    targetCompatibility = JavaVersion.VERSION_17
}

application {
    mainClass.set("com.johnlpage.pocdriver.POCDriver")
}

repositories {
    mavenCentral()
    google()
    gradlePluginPortal()
}

dependencies {
    implementation("ch.qos.logback:logback-classic:1.4.12")
    implementation("org.mongodb:mongodb-driver-sync:4.11.4")
    implementation("commons-cli:commons-cli:1.4")
    implementation("commons-codec:commons-codec:1.15")
    implementation("com.google.code.gson:gson:2.8.9")
    implementation("de.sven-jacobs:loremipsum:1.0")
    implementation("org.apache.commons:commons-math3:3.6.1")
    implementation("org.xerial.snappy:snappy-java:1.1.10.4")
    implementation("com.github.luben:zstd-jni:1.4.9-1")
    testImplementation("junit:junit:4.13.2")
}

tasks {
    jar {
        manifest {
            attributes["Main-Class"] = "com.johnlpage.pocdriver.POCDriver"
        }
    }

    shadowJar {
        manifest {
            attributes["Main-Class"] = "com.johnlpage.pocdriver.POCDriver"
        }
//        archiveBaseName.set("poc-driver")
//        archiveClassifier.set("")
//        archiveVersion.set("$version")
        archiveFileName.set("POCDriver.jar")
        mergeServiceFiles()
    }
}
