/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    java
    application
    id("com.gradleup.shadow") version "8.3.4"
}

group="org.mongodb"
version="0.2-SNAPSHOT"
description="poc-driver"

java {
    sourceCompatibility = JavaVersion.VERSION_17
    targetCompatibility = JavaVersion.VERSION_17
}

application {
    mainClass.set("com.johnlpage.pocdriver.POCDriver")
}

repositories {
    mavenCentral()
    google()
    gradlePluginPortal()
}

dependencies {
    implementation(libs.logback.classic)
    implementation(libs.mongodb.driver.sync)
    implementation(libs.commons.cli)
    implementation(libs.commons.codec)
    implementation(libs.gson)
    implementation(libs.loremipsum)
    implementation(libs.commons.math3)
    implementation(libs.snappy.java)
    implementation(libs.zstd)
    testImplementation(libs.junit)
}

tasks {
    jar {
        manifest {
            attributes["Main-Class"] = "com.johnlpage.pocdriver.POCDriver"
        }
    }

    shadowJar {
        manifest {
            attributes["Main-Class"] = "com.johnlpage.pocdriver.POCDriver"
        }
//        archiveBaseName.set("poc-driver")
//        archiveClassifier.set("")
//        archiveVersion.set("$version")
        archiveFileName.set("POCDriver.jar")
        mergeServiceFiles()
    }
}
