/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

rootProject.name = "poc-driver"

var gradleVer = GradleVersion.current()
var minimumVersion = GradleVersion.version("8.10")
if (gradleVer < minimumVersion) {
    throw GradleScriptException("this build cannot be run with gradle < $minimumVersion. " +
            "current detection version is $gradleVer. " +
            "Use newer gradle or (better yet) use the wrapper", Throwable())
}
